languageCode = "en"
languageName = "English"
weight = 1
title = "UW Debate"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2 2006"
  logo = "logo small.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "University of Waterloo Debate Society"
  image = "logo.png"
  headline = ""
  bio = "Waterloo’s varsity debate team!"
  links = [
    { instagram = "https://instagram.com/uwdebate" },
    { youtube = "https://youtube.com/@uwdebate" },
    { discord = "https://discord.gg/DzF6ubWkRc" },
    { facebook = "https://www.facebook.com/uwdebate" },
    { email = "mailto:debateuw@gmail.com" },
    { link = "https://linktr.ee/uwdebate" },
  ]
